<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\Pivot;

class PostTag extends Pivot
{
   protected  $table ='post_tag';

   public  static function  boot()
   {
       parent::boot(); // TODO: Change the autogenerated stub

       static::created(function ($item){
           dd('Created event', $item);
       });

       static::deleted(function ($item){
           dd('Deleted event', $item);
       });
   }
}
